#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace customerProfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IVRCPR")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["IVRCPRConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Rule> Rules
		{
			get
			{
				return this.GetTable<Rule>();
			}
		}
		
		public System.Data.Linq.Table<RuleMetric> RuleMetrics
		{
			get
			{
				return this.GetTable<RuleMetric>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetOverride")]
		public ISingleResult<GetOverrideResult> GetOverride([global::System.Data.Linq.Mapping.ParameterAttribute(Name="POS", DbType="NVarChar(3)")] string pOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Itin", DbType="NVarChar(50)")] string itin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pOS, itin);
			return ((ISingleResult<GetOverrideResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rules")]
	public partial class Rule
	{
		
		private System.Nullable<int> _RuleID;
		
		private System.Nullable<int> _RuleRank;
		
		private string _POSCode;
		
		public Rule()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RuleID", DbType="Int")]
		public System.Nullable<int> RuleID
		{
			get
			{
				return this._RuleID;
			}
			set
			{
				if ((this._RuleID != value))
				{
					this._RuleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RuleRank", DbType="Int")]
		public System.Nullable<int> RuleRank
		{
			get
			{
				return this._RuleRank;
			}
			set
			{
				if ((this._RuleRank != value))
				{
					this._RuleRank = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSCode", DbType="NVarChar(3)")]
		public string POSCode
		{
			get
			{
				return this._POSCode;
			}
			set
			{
				if ((this._POSCode != value))
				{
					this._POSCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RuleMetric")]
	public partial class RuleMetric
	{
		
		private System.Nullable<int> _RuleID;
		
		private string _Metric;
		
		private System.Nullable<int> _MetricValue;
		
		public RuleMetric()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RuleID", DbType="Int")]
		public System.Nullable<int> RuleID
		{
			get
			{
				return this._RuleID;
			}
			set
			{
				if ((this._RuleID != value))
				{
					this._RuleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Metric", DbType="VarChar(100)")]
		public string Metric
		{
			get
			{
				return this._Metric;
			}
			set
			{
				if ((this._Metric != value))
				{
					this._Metric = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetricValue", DbType="Int")]
		public System.Nullable<int> MetricValue
		{
			get
			{
				return this._MetricValue;
			}
			set
			{
				if ((this._MetricValue != value))
				{
					this._MetricValue = value;
				}
			}
		}
	}
	
	public partial class GetOverrideResult
	{
		
		private string _MenuTypeName;
		
		private int _MessageID;
		
		private string _OptionList;
		
		private System.Nullable<bool> _RepeatMenu;
		
		public GetOverrideResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuTypeName", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string MenuTypeName
		{
			get
			{
				return this._MenuTypeName;
			}
			set
			{
				if ((this._MenuTypeName != value))
				{
					this._MenuTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageID", DbType="Int NOT NULL")]
		public int MessageID
		{
			get
			{
				return this._MessageID;
			}
			set
			{
				if ((this._MessageID != value))
				{
					this._MessageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionList", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string OptionList
		{
			get
			{
				return this._OptionList;
			}
			set
			{
				if ((this._OptionList != value))
				{
					this._OptionList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatMenu", DbType="Bit")]
		public System.Nullable<bool> RepeatMenu
		{
			get
			{
				return this._RepeatMenu;
			}
			set
			{
				if ((this._RepeatMenu != value))
				{
					this._RepeatMenu = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
